name: release

on:
  create:
    tags:
      - '*'

jobs:
  release:
    if: (github.event_name == 'create' && github.event.ref_type == 'tag')
    runs-on: ubuntu-latest
    steps:
      - name: 'Prepare branch name'
        run: >
          echo "refName=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: 'Checkout relevant branch'
        uses: actions/checkout@v3
        with:
          ref: ${{ env.refName }}
          fetch-depth: 0

      - name: 'Create release'
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
          JRELEASER_SLACK_WEBHOOK: ${{ secrets.JRELEASER_SLACK_WEBHOOK }}
        run: ./mvnw --no-transfer-progress -Pjreleaser -pl :neo4j-ogm-spring-parent jreleaser:full-release
